### ISSUE TITLE
Clang-c/Index.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [Gnurou/kdevelop#10]
Trying to compile clang branch. Did I missed something? Clang is in place and working

<pre>[ 12%] Built target kdev4cppparser
Scanning dependencies of target kdevclang_automoc
Generating clangparsejob.moc
[ 12%] Built target kdevclang_automoc
Scanning dependencies of target kdevclang
[ 13%] Building CXX object languages/cpp/clang/CMakeFiles/kdevclang.dir/kdevclang_automoc.o
[ 13%] Building CXX object languages/cpp/clang/CMakeFiles/kdevclang.dir/clangparsejob.o
/home/constantine/src/kdevelop/languages/cpp/clang/clangparsejob.cpp:49:27: fatal error: clang-c/Index.h: No such file or directory
compilation terminated.
make[2]: *** [languages/cpp/clang/CMakeFiles/kdevclang.dir/clangparsejob.o] Error 1
make[1]: *** [languages/cpp/clang/CMakeFiles/kdevclang.dir/all] Error 2
make: *** [all] Error 2
</pre>

Ubuntu 12.10

**Comment by ghost** [comment]
There was no development libraries for clang, the problem solves by installing libclang-dev from ubuntu's repository

**Comment by ghost** [comment]
Nope, just installed clang 3.3 from [llvm's quantal ppa repository](http://llvm.org/apt/) and the error happens again, despite the fact that libclang-dev and other development libraries are installed:

<pre>
constantine@eudaimonia:~$ dpkg -s libclang-dev
Package: libclang-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 46243
Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
Architecture: amd64
Source: llvm-toolchain-snapshot
Version: 1:3.3~svn181149-1~exp1
Depends: libstdc++6-4.7-dev, libclang1 (= 1:3.3~svn181149-1~exp1), libclang-common-dev (= 1:3.3~svn181149-1~exp1)
</pre>

**Comment by Gnurou** [comment]
Do you have a /usr/include/clang-c/Index.h file on your system? If not, can you check the contents of the libclang-dev package and tell me where the file is located?

**Comment by ghost** [comment]
No, there's no clang-c in include folder, here is the full path:

<pre>/usr/lib/llvm-3.3/include/clang-c/Index.h</pre>

**Comment by ghost** [comment]
Ok. it seems the path of v3.3 was weird, manually installed binaries of v3.2 from [the site](http://llvm.org/releases/download.html) and now it compiles properly
