### ISSUE TITLE
Error: ‘class KDevelop::OutputModel’ has no member named ‘flushLineBuffer’

### ISSUE THREAD

**Issue by ghost** [Gnurou/kdevelop#12]
Compiling clang branch

<pre>
[ 59%] Building CXX object projectmanagers/cmake/CMakeFiles/kdevcmakemanager.dir/testing/ctestrunjob.o
/home/constantine/src/kdevelop/projectmanagers/cmake/testing/ctestrunjob.cpp: In member function ‘void CTestRunJob::processFinished(KJob*)’:
/home/constantine/src/kdevelop/projectmanagers/cmake/testing/ctestrunjob.cpp:142:16: error: ‘class KDevelop::OutputModel’ has no member named ‘flushLineBuffer’
make[2]: *** [projectmanagers/cmake/CMakeFiles/kdevcmakemanager.dir/testing/ctestrunjob.o] Error 1
make[1]: *** [projectmanagers/cmake/CMakeFiles/kdevcmakemanager.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by Gnurou** [comment]
Mmmm weird - are you compiling with the right version of KDevplatform? It must match the version of KDevelop used, i.e. 4.5 here.

**Comment by ghost** [comment]
Yea, you're right, I haven't checkout version 1.5 of kdevplatform. It compiles properly now, but when I'm trying to create a project, as cmake window closes it crashes with segmentation fault no matter what. I give up :grinning: Thanks for answers!

**Comment by Gnurou** [comment]
It's very likely that the parser crashes on anything else than simple files - as I said, it is very very early work. Thanks for trying though! ;)
